language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed dacnc/udagram-api-feed:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dacnc/udagram-api-feed:v1

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user dacnc/udagram-api-user:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dacnc/udagram-api-user:v1

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend dacnc/udagram-frontend:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dacnc/udagram-frontend:v1

  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy dacnc/reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dacnc/reverseproxy:v1
