apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
    spec:
      containers:
        - image: dacnc/udagram-frontend:v8
          name: udagram-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
      restartPolicy: Always