apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
    spec:
      containers:
        - image: dacnc/udagram-frontend:latest
          name: udagram-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always